site_name: Raj Pandurangan
site_url: https://mydomain.org/mysite

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

nav:
  - Home: index.md
  - AWS External Surface:
      - Index: awsorgscan/index.md
      - Getting Started: awsorgscan/getting-started.md
      - Building: awsorgscan/building.md
      - Services: awsorgscan/services.md
      - Output Format: awsorgscan/output-format.md
      - Sample Output: awsorgscan/sample-output.md
      - FAQ: awsorgscan/faq.md
  - Blog: blog/

plugins:
  - search
  - blog:
extra_css:
  - styles/extra.css